version: "3.9"

services:
  squadcms:
    build:
      context: .
      dockerfile: Dockerfile
    image: squadcms:latest
    container_name: squadcms
    restart: unless-stopped
    ports:
      - "4000:4000"
